### ISSUE TITLE
 aioflask with Flask>=3.0

### ISSUE THREAD

**Issue by wathika-eng** [pallets-eco/flask-admin#2418] opened 2024-03-06 13:50 UTC
from flask import _request_ctx_stack
ImportError: cannot import name '_request_ctx_stack' from 'flask'

Tried fixing with https://github.com/miguelgrinberg/aioflask/issues/10

**Comment by samuelhwilliams** [comment] 2024-07-06 07:17
Is this an issue in Flask-Admin directly, or some other package?

**Comment by samuelhwilliams** [comment] 2024-07-06 07:19
Closing as a duplicate of https://github.com/pallets-eco/flask-admin/issues/2413. I think there's probably some overlap here, but if you mean something slightly different please do open another issue with some additional information.

**Closed by samuelhwilliams** 2024-07-06 07:19 UTC
